spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microapple
    username: microapple
    password: microapple123
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.ncode.microapple: DEBUG