server:
  port: 8090

spring:
  application:
    name: microapple
  
  datasource:
    url: jdbc:postgresql://localhost:5432/microapple
    username: microapple
    password: microapple123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

logging:
  level:
    com.ncode.microapple: DEBUG
    org.springframework.boot.autoconfigure: INFO

# Kafka configuration
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: microapple-app
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Iceberg configuration
iceberg:
  catalog:
    uri: http://localhost:8181
  warehouse: s3://iceberg-warehouse/